### ISSUE TITLE
composer require manukminasyan/laravel-permission-manager

### ISSUE THREAD

**Issue by ttimburwa** [ManukMinasyan/Laravel-Permission-Manager#3]
[InvalidArgumentException]                                                   
  Could not find a version of package manukminasyan/laravel-permission-manage  
  r matching your minimum-stability (stable). Require it with an explicit ver  
  sion constraint allowing its desired stability.

**Comment by ManukMinasyan** [comment]
![Capture](https://user-images.githubusercontent.com/2556185/63496401-e83d0480-c4d2-11e9-8e20-3f8f2c785fad.PNG)

Please tell me how you are doing the installation, thanks.
